import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ReservationProject.settings')
from django import setup
setup()

from ReservationApp.models import Facility,RoomType,Room

facility = Facility(facility_name="○○宿",picture_url="marumaru_pic.jpg")
facility.save()
facility1=Facility(facility_name="△△ホテル",picture_url="sankaku_pic.jpg")
facility1.save()
facility2=Facility(facility_name="××温泉旅館",picture_url="batubatu_pic.jpg")
facility2.save()
print(Facility.objects.all())

room_type = RoomType(type_name="スタンダード",capacity=5,type_fee=5000)
room_type.save()
room_type1=RoomType(type_name="プレミアム",capacity=10,type_fee=10000)
room_type1.save()
print(RoomType.objects.all())
room1=Room(room_number=101,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=1))
room1.save()
room2=Room(room_number=102,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=1))
room2.save()
room3=Room(room_number=103,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=1))
room3.save()
room4=Room(room_number=104,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=2))
room4.save()
room5=Room(room_number=105,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=2))
room5.save()
room6=Room(room_number=106,facility=Facility.objects.get(pk=1),room_type=RoomType.objects.get(pk=2))
room6.save()
room7=Room(room_number=107,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=1))
room7.save()
room8=Room(room_number=108,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=1))
room8.save()
room9=Room(room_number=109,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=1))
room9.save()
room10=Room(room_number=110,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=2))
room10.save()
room11=Room(room_number=111,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=2))
room11.save()
room12=Room(room_number=112,facility=Facility.objects.get(pk=2),room_type=RoomType.objects.get(pk=2))
room12.save()
room13=Room(room_number=113,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=1))
room13.save()
room14=Room(room_number=114,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=1))
room14.save()
room15=Room(room_number=115,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=1))
room15.save()
room16=Room(room_number=116,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=2))
room16.save()
room17=Room(room_number=117,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=2))
room17.save()
room18=Room(room_number=118,facility=Facility.objects.get(pk=3),room_type=RoomType.objects.get(pk=2))
room18.save()